# -*- coding: utf-8 -*-
"""week4-A108060044-林恩.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjPWwG9rMD2QEXrxEoHlBaTetQiVjIk_
"""

print("hello world")

print(1+1)

print("A108060116huang yi xuan")